### ISSUE TITLE
초기 상태에서 훔쳐오기 crash

### ISSUE THREAD

**Issue by svclaw2000** [boostcampwm-2021/Android08-Ratatouille#135]
## To Do List

- [ ] 내 레시피가 비어있는 상태에서 훔쳐오기 했을 때 crash 나는 문제

**Comment by azzyjk** [comment]
레시피 추가화면을 가지않고 바로 훔쳐오기하면 발생하는 문제로 밝혀짐.
레시피 추가화면에서 RecipeType을 받아오는데 만약 들르지 않고 홈쳐오기 할 시 존재하지 않는 RecipeType을 받아와서 저장을 할 수 없게 된다.
추후 레시피 개요 들어갈 시 RecipeType 업데이트 하도록 코드 수정 예정
