### ISSUE TITLE
Firebase Storage no token 이슈

### ISSUE THREAD

**Issue by svclaw2000** [boostcampwm-2021/Android08-Ratatouille#139]
## To Do List

- [ ] 레시피 업로드 시 지연되는 문제

**Comment by azzyjk** [comment]
레시피 업로드시 지연되는 것이 아닌 firebase 인증을 사용하지 않아 뜨는 문구로 확인됨.
profiler를 확인했을 때 해당 문구가 뜨는 중에도 이미지는 전송되는 것으로 확인됨.
